

CREATE TABLE IF NOT EXISTS Salesperson (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    Name VARCHAR(100),
    Birth_Date DATE,
    Date_Created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
 
CREATE TABLE if NOT EXISTS  Distributor (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Country_Of_Origin VARCHAR(50) NOT NULL
);
 


CREATE TABLE IF NOT EXISTS Category (
    ID INT AUTO_INCREMENT PRIMARY KEY ,
    Name VARCHAR(15) NOT NULL,
    Phone_Number VARCHAR(10) NOT NULL,
    Manager_ID INT UNIQUE NOT NULL,
    FOREIGN KEY (Manager_ID) REFERENCES Salesperson(ID)
);
 
CREATE TABLE IF NOT EXISTS Car(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Car_weight INT(4) NOT NULL,
    Color VARCHAR(12) NOT NULL,
    Price FLOAT NOT NULL,
    Category_ID INT NOT NULL,
    Distributor_ID INT NOT NULL,
    FOREIGN KEY (Category_ID) REFERENCES Category(ID),
    FOREIGN KEY (Distributor_ID) REFERENCES Distributor(ID)
);
 


CREATE TABLE IF NOT EXISTS Customer (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(45) NOT NULL,
    Date_Created DATE NOT NULL
);
 
CREATE TABLE IF NOT EXISTS Sale (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Car_ID INT NOT NULL,
    Customer_ID INT(9) NOT NULL,
    Date DATE NOT NULL,
    FOREIGN KEY (Car_ID) REFERENCES Car(ID),
    FOREIGN KEY (Customer_ID) REFERENCES Customer(ID)
);
 
CREATE TABLE IF NOT EXISTS Spare_Parts (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Brand VARCHAR(255) NOT NULL,
    Price DECIMAL(10, 2)
);

CREATE TABLE IF NOT EXISTS Spare_Parts_Car(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Car_ID INT NOT NULL,
    Sparepart_ID INT,
    FOREIGN KEY (Car_ID) REFERENCES Car(ID),
    FOREIGN KEY (Sparepart_ID) REFERENCES Spare_Parts(ID)
);

 



 
