services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./database/init_create_inserts_demo.sql:/docker-entrypoint-initdb.d/init.sql
  phpMyAdmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_Arbitrary: 1

  php-environment:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80
# USAGE:
# download docker desktop, and make sure the engine is running
# while on the yml folder run: docker compose up
# then connect to myphpadmin on localhost:8080 from a browser
# login with root:root

# To connect to using a driver(for example VSCode SQLTools with MySQL), use the following:
# host: localhost
# port: 3306
# username: root
# password: root
# database: dealership

# other commands that may be useful:

# docker container ls (shows the port and the container id)
# get the mysql container ip
# docker inspect <mysql_container_id>

# Connect to the mysql container from the terminal
# docker exec -it <mysql_container_id> bash

# Connect to the mysql from the terminal
# mysql -u root -p (password: root)

# Find the version of the mysql
# mysql --version

# Create a database
# CREATE DATABASE dealership;

